import type { Curriculum } from "./types";

export const hsk1: Curriculum = {
  level: "hsk1",
  label: "HSK 1",
  emoji: "🐣",
  lessons: [
    {
      id: 1,
      title: "Hello & me",
      vocab: [
        { hanzi: "你", pinyin: "nǐ", meaning: "you" },
        { hanzi: "好", pinyin: "hǎo", meaning: "good" },
        { hanzi: "我", pinyin: "wǒ", meaning: "I, me" },
        { hanzi: "他", pinyin: "tā", meaning: "he, him" },
        { hanzi: "她", pinyin: "tā", meaning: "she, her" },
      ],
      sentence: { hanzi: "你好！我是小明。", pinyin: "Nǐ hǎo! Wǒ shì Xiǎo Míng.", meaning: "Hello! I am Xiao Ming." },
    },
    {
      id: 2,
      title: "Polite words",
      vocab: [
        { hanzi: "谢谢", pinyin: "xièxie", meaning: "thank you" },
        { hanzi: "不客气", pinyin: "bú kèqi", meaning: "you're welcome" },
        { hanzi: "对不起", pinyin: "duìbuqǐ", meaning: "sorry" },
        { hanzi: "没关系", pinyin: "méi guānxi", meaning: "no problem" },
        { hanzi: "再见", pinyin: "zàijiàn", meaning: "goodbye" },
      ],
      sentence: { hanzi: "谢谢你！再见。", pinyin: "Xièxie nǐ! Zàijiàn.", meaning: "Thank you! Goodbye." },
    },
    {
      id: 3,
      title: "Numbers 1–5",
      vocab: [
        { hanzi: "一", pinyin: "yī", meaning: "one" },
        { hanzi: "二", pinyin: "èr", meaning: "two" },
        { hanzi: "三", pinyin: "sān", meaning: "three" },
        { hanzi: "四", pinyin: "sì", meaning: "four" },
        { hanzi: "五", pinyin: "wǔ", meaning: "five" },
      ],
      sentence: { hanzi: "我有三个苹果。", pinyin: "Wǒ yǒu sān gè píngguǒ.", meaning: "I have three apples." },
    },
    {
      id: 4,
      title: "Numbers 6–10",
      vocab: [
        { hanzi: "六", pinyin: "liù", meaning: "six" },
        { hanzi: "七", pinyin: "qī", meaning: "seven" },
        { hanzi: "八", pinyin: "bā", meaning: "eight" },
        { hanzi: "九", pinyin: "jiǔ", meaning: "nine" },
        { hanzi: "十", pinyin: "shí", meaning: "ten" },
      ],
      sentence: { hanzi: "今年我九岁。", pinyin: "Jīnnián wǒ jiǔ suì.", meaning: "I am nine years old this year." },
    },
    {
      id: 5,
      title: "Family",
      vocab: [
        { hanzi: "爸爸", pinyin: "bàba", meaning: "dad" },
        { hanzi: "妈妈", pinyin: "māma", meaning: "mom" },
        { hanzi: "儿子", pinyin: "érzi", meaning: "son" },
        { hanzi: "女儿", pinyin: "nǚ'ér", meaning: "daughter" },
        { hanzi: "朋友", pinyin: "péngyou", meaning: "friend" },
      ],
      sentence: { hanzi: "她是我妈妈。", pinyin: "Tā shì wǒ māma.", meaning: "She is my mom." },
    },
    {
      id: 6,
      title: "Be & have",
      vocab: [
        { hanzi: "是", pinyin: "shì", meaning: "to be" },
        { hanzi: "有", pinyin: "yǒu", meaning: "to have" },
        { hanzi: "不", pinyin: "bù", meaning: "not" },
        { hanzi: "没", pinyin: "méi", meaning: "not (have)" },
        { hanzi: "个", pinyin: "gè", meaning: "(measure word)" },
      ],
      sentence: { hanzi: "我有一个朋友。", pinyin: "Wǒ yǒu yí gè péngyou.", meaning: "I have a friend." },
    },
    {
      id: 7,
      title: "Days & time",
      vocab: [
        { hanzi: "今天", pinyin: "jīntiān", meaning: "today" },
        { hanzi: "明天", pinyin: "míngtiān", meaning: "tomorrow" },
        { hanzi: "昨天", pinyin: "zuótiān", meaning: "yesterday" },
        { hanzi: "现在", pinyin: "xiànzài", meaning: "now" },
        { hanzi: "点", pinyin: "diǎn", meaning: "o'clock" },
      ],
      sentence: { hanzi: "现在三点。", pinyin: "Xiànzài sān diǎn.", meaning: "It is three o'clock." },
    },
    {
      id: 8,
      title: "Calendar",
      vocab: [
        { hanzi: "星期", pinyin: "xīngqī", meaning: "week" },
        { hanzi: "月", pinyin: "yuè", meaning: "month" },
        { hanzi: "年", pinyin: "nián", meaning: "year" },
        { hanzi: "日", pinyin: "rì", meaning: "day" },
        { hanzi: "号", pinyin: "hào", meaning: "date, number" },
      ],
      sentence: { hanzi: "今天是五月八号。", pinyin: "Jīntiān shì wǔ yuè bā hào.", meaning: "Today is May 8th." },
    },
    {
      id: 9,
      title: "Action verbs 1",
      vocab: [
        { hanzi: "看", pinyin: "kàn", meaning: "to look, watch" },
        { hanzi: "听", pinyin: "tīng", meaning: "to listen" },
        { hanzi: "说", pinyin: "shuō", meaning: "to speak" },
        { hanzi: "读", pinyin: "dú", meaning: "to read" },
        { hanzi: "写", pinyin: "xiě", meaning: "to write" },
      ],
      sentence: { hanzi: "我喜欢看书。", pinyin: "Wǒ xǐhuan kàn shū.", meaning: "I like reading books." },
    },
    {
      id: 10,
      title: "Action verbs 2",
      vocab: [
        { hanzi: "来", pinyin: "lái", meaning: "to come" },
        { hanzi: "去", pinyin: "qù", meaning: "to go" },
        { hanzi: "吃", pinyin: "chī", meaning: "to eat" },
        { hanzi: "喝", pinyin: "hē", meaning: "to drink" },
        { hanzi: "做", pinyin: "zuò", meaning: "to do, make" },
      ],
      sentence: { hanzi: "我去学校。", pinyin: "Wǒ qù xuéxiào.", meaning: "I go to school." },
    },
    {
      id: 11,
      title: "Question words",
      vocab: [
        { hanzi: "什么", pinyin: "shénme", meaning: "what" },
        { hanzi: "谁", pinyin: "shéi", meaning: "who" },
        { hanzi: "哪", pinyin: "nǎ", meaning: "which" },
        { hanzi: "哪儿", pinyin: "nǎr", meaning: "where" },
        { hanzi: "怎么", pinyin: "zěnme", meaning: "how" },
      ],
      sentence: { hanzi: "你叫什么名字？", pinyin: "Nǐ jiào shénme míngzi?", meaning: "What is your name?" },
    },
    {
      id: 12,
      title: "How many / how much",
      vocab: [
        { hanzi: "多少", pinyin: "duōshǎo", meaning: "how many/much" },
        { hanzi: "几", pinyin: "jǐ", meaning: "how many (small)" },
        { hanzi: "岁", pinyin: "suì", meaning: "years (of age)" },
        { hanzi: "块", pinyin: "kuài", meaning: "yuan (money)" },
        { hanzi: "钱", pinyin: "qián", meaning: "money" },
      ],
      sentence: { hanzi: "这个多少钱？", pinyin: "Zhège duōshǎo qián?", meaning: "How much is this?" },
    },
    {
      id: 13,
      title: "Big & small",
      vocab: [
        { hanzi: "大", pinyin: "dà", meaning: "big" },
        { hanzi: "小", pinyin: "xiǎo", meaning: "small" },
        { hanzi: "多", pinyin: "duō", meaning: "many" },
        { hanzi: "少", pinyin: "shǎo", meaning: "few" },
        { hanzi: "很", pinyin: "hěn", meaning: "very" },
      ],
      sentence: { hanzi: "这只猫很小。", pinyin: "Zhè zhī māo hěn xiǎo.", meaning: "This cat is very small." },
    },
    {
      id: 14,
      title: "Feelings & weather",
      vocab: [
        { hanzi: "高兴", pinyin: "gāoxìng", meaning: "happy" },
        { hanzi: "漂亮", pinyin: "piàoliang", meaning: "pretty" },
        { hanzi: "热", pinyin: "rè", meaning: "hot" },
        { hanzi: "冷", pinyin: "lěng", meaning: "cold" },
        { hanzi: "天气", pinyin: "tiānqì", meaning: "weather" },
      ],
      sentence: { hanzi: "今天天气很热。", pinyin: "Jīntiān tiānqì hěn rè.", meaning: "Today the weather is very hot." },
    },
    {
      id: 15,
      title: "Places",
      vocab: [
        { hanzi: "中国", pinyin: "Zhōngguó", meaning: "China" },
        { hanzi: "北京", pinyin: "Běijīng", meaning: "Beijing" },
        { hanzi: "学校", pinyin: "xuéxiào", meaning: "school" },
        { hanzi: "家", pinyin: "jiā", meaning: "home, family" },
        { hanzi: "商店", pinyin: "shāngdiàn", meaning: "shop" },
      ],
      sentence: { hanzi: "我家在北京。", pinyin: "Wǒ jiā zài Běijīng.", meaning: "My home is in Beijing." },
    },
    {
      id: 16,
      title: "Around town",
      vocab: [
        { hanzi: "饭店", pinyin: "fàndiàn", meaning: "restaurant" },
        { hanzi: "医院", pinyin: "yīyuàn", meaning: "hospital" },
        { hanzi: "火车站", pinyin: "huǒchēzhàn", meaning: "train station" },
        { hanzi: "飞机", pinyin: "fēijī", meaning: "airplane" },
        { hanzi: "出租车", pinyin: "chūzūchē", meaning: "taxi" },
      ],
      sentence: { hanzi: "我们去饭店吃饭。", pinyin: "Wǒmen qù fàndiàn chī fàn.", meaning: "We go to a restaurant to eat." },
    },
    {
      id: 17,
      title: "Food & drink",
      vocab: [
        { hanzi: "米饭", pinyin: "mǐfàn", meaning: "rice (cooked)" },
        { hanzi: "菜", pinyin: "cài", meaning: "vegetable, dish" },
        { hanzi: "苹果", pinyin: "píngguǒ", meaning: "apple" },
        { hanzi: "水", pinyin: "shuǐ", meaning: "water" },
        { hanzi: "茶", pinyin: "chá", meaning: "tea" },
      ],
      sentence: { hanzi: "我想喝水。", pinyin: "Wǒ xiǎng hē shuǐ.", meaning: "I want to drink water." },
    },
    {
      id: 18,
      title: "Things at home",
      vocab: [
        { hanzi: "书", pinyin: "shū", meaning: "book" },
        { hanzi: "桌子", pinyin: "zhuōzi", meaning: "table" },
        { hanzi: "椅子", pinyin: "yǐzi", meaning: "chair" },
        { hanzi: "电视", pinyin: "diànshì", meaning: "TV" },
        { hanzi: "电脑", pinyin: "diànnǎo", meaning: "computer" },
      ],
      sentence: { hanzi: "桌子上有一本书。", pinyin: "Zhuōzi shàng yǒu yì běn shū.", meaning: "There is a book on the table." },
    },
    {
      id: 19,
      title: "More things",
      vocab: [
        { hanzi: "电话", pinyin: "diànhuà", meaning: "telephone" },
        { hanzi: "杯子", pinyin: "bēizi", meaning: "cup" },
        { hanzi: "衣服", pinyin: "yīfu", meaning: "clothes" },
        { hanzi: "东西", pinyin: "dōngxi", meaning: "thing, stuff" },
        { hanzi: "本", pinyin: "běn", meaning: "(measure: books)" },
      ],
      sentence: { hanzi: "这是我的杯子。", pinyin: "Zhè shì wǒ de bēizi.", meaning: "This is my cup." },
    },
    {
      id: 20,
      title: "Time of day",
      vocab: [
        { hanzi: "上午", pinyin: "shàngwǔ", meaning: "morning" },
        { hanzi: "中午", pinyin: "zhōngwǔ", meaning: "noon" },
        { hanzi: "下午", pinyin: "xiàwǔ", meaning: "afternoon" },
        { hanzi: "下雨", pinyin: "xiàyǔ", meaning: "to rain" },
        { hanzi: "分钟", pinyin: "fēnzhōng", meaning: "minute" },
      ],
      sentence: { hanzi: "明天下午下雨。", pinyin: "Míngtiān xiàwǔ xiàyǔ.", meaning: "It will rain tomorrow afternoon." },
    },
    {
      id: 21,
      title: "Daily verbs",
      vocab: [
        { hanzi: "工作", pinyin: "gōngzuò", meaning: "to work" },
        { hanzi: "学习", pinyin: "xuéxí", meaning: "to study" },
        { hanzi: "认识", pinyin: "rènshi", meaning: "to know (someone)" },
        { hanzi: "想", pinyin: "xiǎng", meaning: "to want, miss" },
        { hanzi: "爱", pinyin: "ài", meaning: "to love" },
      ],
      sentence: { hanzi: "我爱学习汉语。", pinyin: "Wǒ ài xuéxí Hànyǔ.", meaning: "I love studying Chinese." },
    },
    {
      id: 22,
      title: "Like & live",
      vocab: [
        { hanzi: "喜欢", pinyin: "xǐhuan", meaning: "to like" },
        { hanzi: "请", pinyin: "qǐng", meaning: "please" },
        { hanzi: "叫", pinyin: "jiào", meaning: "to be called" },
        { hanzi: "住", pinyin: "zhù", meaning: "to live" },
        { hanzi: "在", pinyin: "zài", meaning: "at, in" },
      ],
      sentence: { hanzi: "我住在北京。", pinyin: "Wǒ zhù zài Běijīng.", meaning: "I live in Beijing." },
    },
    {
      id: 23,
      title: "More verbs",
      vocab: [
        { hanzi: "开", pinyin: "kāi", meaning: "to open, drive" },
        { hanzi: "坐", pinyin: "zuò", meaning: "to sit" },
        { hanzi: "睡觉", pinyin: "shuìjiào", meaning: "to sleep" },
        { hanzi: "回", pinyin: "huí", meaning: "to return" },
        { hanzi: "打电话", pinyin: "dǎ diànhuà", meaning: "to phone" },
      ],
      sentence: { hanzi: "我现在回家。", pinyin: "Wǒ xiànzài huí jiā.", meaning: "I am going home now." },
    },
    {
      id: 24,
      title: "Buy & can",
      vocab: [
        { hanzi: "买", pinyin: "mǎi", meaning: "to buy" },
        { hanzi: "会", pinyin: "huì", meaning: "can, will" },
        { hanzi: "能", pinyin: "néng", meaning: "to be able to" },
        { hanzi: "这", pinyin: "zhè", meaning: "this" },
        { hanzi: "那", pinyin: "nà", meaning: "that" },
      ],
      sentence: { hanzi: "我会说汉语。", pinyin: "Wǒ huì shuō Hànyǔ.", meaning: "I can speak Chinese." },
    },
    {
      id: 25,
      title: "Little words",
      vocab: [
        { hanzi: "也", pinyin: "yě", meaning: "also" },
        { hanzi: "都", pinyin: "dōu", meaning: "all" },
        { hanzi: "太", pinyin: "tài", meaning: "too" },
        { hanzi: "和", pinyin: "hé", meaning: "and" },
        { hanzi: "的", pinyin: "de", meaning: "(possessive)" },
      ],
      sentence: { hanzi: "我和爸爸都喜欢茶。", pinyin: "Wǒ hé bàba dōu xǐhuan chá.", meaning: "Dad and I both like tea." },
    },
    {
      id: 26,
      title: "Particles",
      vocab: [
        { hanzi: "了", pinyin: "le", meaning: "(completed action)" },
        { hanzi: "吗", pinyin: "ma", meaning: "(yes/no question)" },
        { hanzi: "呢", pinyin: "ne", meaning: "(question)" },
        { hanzi: "我们", pinyin: "wǒmen", meaning: "we, us" },
        { hanzi: "你们", pinyin: "nǐmen", meaning: "you (plural)" },
      ],
      sentence: { hanzi: "你吃饭了吗？", pinyin: "Nǐ chī fàn le ma?", meaning: "Have you eaten?" },
    },
    {
      id: 27,
      title: "Position",
      vocab: [
        { hanzi: "前面", pinyin: "qiánmiàn", meaning: "in front" },
        { hanzi: "后面", pinyin: "hòumiàn", meaning: "behind" },
        { hanzi: "上面", pinyin: "shàngmiàn", meaning: "above" },
        { hanzi: "下面", pinyin: "xiàmiàn", meaning: "below" },
        { hanzi: "里", pinyin: "lǐ", meaning: "inside" },
      ],
      sentence: { hanzi: "猫在椅子下面。", pinyin: "Māo zài yǐzi xiàmiàn.", meaning: "The cat is under the chair." },
    },
    {
      id: 28,
      title: "People",
      vocab: [
        { hanzi: "老师", pinyin: "lǎoshī", meaning: "teacher" },
        { hanzi: "学生", pinyin: "xuéshēng", meaning: "student" },
        { hanzi: "医生", pinyin: "yīshēng", meaning: "doctor" },
        { hanzi: "先生", pinyin: "xiānsheng", meaning: "Mr." },
        { hanzi: "小姐", pinyin: "xiǎojiě", meaning: "Miss" },
      ],
      sentence: { hanzi: "她是我们的老师。", pinyin: "Tā shì wǒmen de lǎoshī.", meaning: "She is our teacher." },
    },
    {
      id: 29,
      title: "Names & language",
      vocab: [
        { hanzi: "名字", pinyin: "míngzi", meaning: "name" },
        { hanzi: "字", pinyin: "zì", meaning: "character" },
        { hanzi: "汉语", pinyin: "Hànyǔ", meaning: "Chinese (language)" },
        { hanzi: "中国人", pinyin: "Zhōngguórén", meaning: "Chinese person" },
        { hanzi: "他们", pinyin: "tāmen", meaning: "they (m)" },
      ],
      sentence: { hanzi: "我的名字是小红。", pinyin: "Wǒ de míngzi shì Xiǎo Hóng.", meaning: "My name is Xiao Hong." },
    },
    {
      id: 30,
      title: "Wrap-up",
      vocab: [
        { hanzi: "好吃", pinyin: "hǎochī", meaning: "delicious" },
        { hanzi: "很好", pinyin: "hěn hǎo", meaning: "very good" },
        { hanzi: "再", pinyin: "zài", meaning: "again" },
        { hanzi: "见", pinyin: "jiàn", meaning: "to see, meet" },
        { hanzi: "请问", pinyin: "qǐngwèn", meaning: "may I ask" },
      ],
      sentence: { hanzi: "请问，茶好喝吗？", pinyin: "Qǐngwèn, chá hǎohē ma?", meaning: "Excuse me, is the tea good?" },
    },
  ],
};
