import type { Curriculum } from "./types";

export const hsk2: Curriculum = {
  level: "hsk2",
  label: "HSK 2",
  emoji: "🐼",
  lessons: [
    {
      id: 1,
      title: "Colors & snow",
      vocab: [
        { hanzi: "白", pinyin: "bái", meaning: "white" },
        { hanzi: "黑", pinyin: "hēi", meaning: "black" },
        { hanzi: "红", pinyin: "hóng", meaning: "red" },
        { hanzi: "颜色", pinyin: "yánsè", meaning: "color" },
        { hanzi: "雪", pinyin: "xuě", meaning: "snow" },
      ],
      sentence: { hanzi: "雪是白的。", pinyin: "Xuě shì bái de.", meaning: "Snow is white." },
    },
    {
      id: 2,
      title: "Big & old, small & new",
      vocab: [
        { hanzi: "长", pinyin: "cháng", meaning: "long" },
        { hanzi: "短", pinyin: "duǎn", meaning: "short" },
        { hanzi: "高", pinyin: "gāo", meaning: "tall, high" },
        { hanzi: "旧", pinyin: "jiù", meaning: "old (thing)" },
        { hanzi: "真", pinyin: "zhēn", meaning: "really, true" },
      ],
      sentence: { hanzi: "这条路真长。", pinyin: "Zhè tiáo lù zhēn cháng.", meaning: "This road is really long." },
    },
    {
      id: 3,
      title: "Time & speed",
      vocab: [
        { hanzi: "快", pinyin: "kuài", meaning: "fast" },
        { hanzi: "慢", pinyin: "màn", meaning: "slow" },
        { hanzi: "早", pinyin: "zǎo", meaning: "early" },
        { hanzi: "晚", pinyin: "wǎn", meaning: "late" },
        { hanzi: "时间", pinyin: "shíjiān", meaning: "time" },
      ],
      sentence: { hanzi: "时间过得真快。", pinyin: "Shíjiān guò de zhēn kuài.", meaning: "Time passes really fast." },
    },
    {
      id: 4,
      title: "Where things are",
      vocab: [
        { hanzi: "远", pinyin: "yuǎn", meaning: "far" },
        { hanzi: "近", pinyin: "jìn", meaning: "near" },
        { hanzi: "路", pinyin: "lù", meaning: "road" },
        { hanzi: "旁边", pinyin: "pángbiān", meaning: "beside" },
        { hanzi: "外", pinyin: "wài", meaning: "outside" },
      ],
      sentence: { hanzi: "我家就在路旁边。", pinyin: "Wǒ jiā jiù zài lù pángbiān.", meaning: "My home is right beside the road." },
    },
    {
      id: 5,
      title: "How are you feeling?",
      vocab: [
        { hanzi: "忙", pinyin: "máng", meaning: "busy" },
        { hanzi: "累", pinyin: "lèi", meaning: "tired" },
        { hanzi: "错", pinyin: "cuò", meaning: "wrong" },
        { hanzi: "对", pinyin: "duì", meaning: "right, correct" },
        { hanzi: "一起", pinyin: "yìqǐ", meaning: "together" },
      ],
      sentence: { hanzi: "我今天真的很忙。", pinyin: "Wǒ jīntiān zhēn de hěn máng.", meaning: "I'm really busy today." },
    },
    {
      id: 6,
      title: "Give & help",
      vocab: [
        { hanzi: "给", pinyin: "gěi", meaning: "to give" },
        { hanzi: "用", pinyin: "yòng", meaning: "to use" },
        { hanzi: "让", pinyin: "ràng", meaning: "to let" },
        { hanzi: "帮助", pinyin: "bāngzhù", meaning: "to help" },
        { hanzi: "帮忙", pinyin: "bāngmáng", meaning: "to lend a hand" },
      ],
      sentence: { hanzi: "请给我一杯水。", pinyin: "Qǐng gěi wǒ yì bēi shuǐ.", meaning: "Please give me a cup of water." },
    },
    {
      id: 7,
      title: "Daily routine",
      vocab: [
        { hanzi: "起床", pinyin: "qǐchuáng", meaning: "to get up" },
        { hanzi: "洗", pinyin: "xǐ", meaning: "to wash" },
        { hanzi: "穿", pinyin: "chuān", meaning: "to wear" },
        { hanzi: "上班", pinyin: "shàngbān", meaning: "to go to work" },
        { hanzi: "休息", pinyin: "xiūxi", meaning: "to rest" },
      ],
      sentence: { hanzi: "我七点起床。", pinyin: "Wǒ qī diǎn qǐchuáng.", meaning: "I get up at seven." },
    },
    {
      id: 8,
      title: "Move your body",
      vocab: [
        { hanzi: "站", pinyin: "zhàn", meaning: "to stand" },
        { hanzi: "走", pinyin: "zǒu", meaning: "to walk" },
        { hanzi: "跑", pinyin: "pǎo", meaning: "to run" },
        { hanzi: "跳", pinyin: "tiào", meaning: "to jump" },
        { hanzi: "进", pinyin: "jìn", meaning: "to enter" },
      ],
      sentence: { hanzi: "别跑，慢慢走。", pinyin: "Bié pǎo, mànman zǒu.", meaning: "Don't run — walk slowly." },
    },
    {
      id: 9,
      title: "Play & laugh",
      vocab: [
        { hanzi: "玩", pinyin: "wán", meaning: "to play" },
        { hanzi: "笑", pinyin: "xiào", meaning: "to laugh, smile" },
        { hanzi: "唱", pinyin: "chàng", meaning: "to sing" },
        { hanzi: "等", pinyin: "děng", meaning: "to wait" },
        { hanzi: "完", pinyin: "wán", meaning: "to finish" },
      ],
      sentence: { hanzi: "我们一起玩吧！", pinyin: "Wǒmen yìqǐ wán ba!", meaning: "Let's play together!" },
    },
    {
      id: 10,
      title: "Siblings & everyone",
      vocab: [
        { hanzi: "哥哥", pinyin: "gēge", meaning: "elder brother" },
        { hanzi: "姐姐", pinyin: "jiějie", meaning: "elder sister" },
        { hanzi: "弟弟", pinyin: "dìdi", meaning: "younger brother" },
        { hanzi: "妹妹", pinyin: "mèimei", meaning: "younger sister" },
        { hanzi: "大家", pinyin: "dàjiā", meaning: "everyone" },
      ],
      sentence: { hanzi: "我有一个姐姐和一个弟弟。", pinyin: "Wǒ yǒu yí gè jiějie hé yí gè dìdi.", meaning: "I have an elder sister and a younger brother." },
    },
    {
      id: 11,
      title: "Body & gender",
      vocab: [
        { hanzi: "身体", pinyin: "shēntǐ", meaning: "body" },
        { hanzi: "眼睛", pinyin: "yǎnjing", meaning: "eye" },
        { hanzi: "男", pinyin: "nán", meaning: "male" },
        { hanzi: "女", pinyin: "nǚ", meaning: "female" },
        { hanzi: "男人", pinyin: "nánrén", meaning: "man" },
      ],
      sentence: { hanzi: "她的眼睛很大。", pinyin: "Tā de yǎnjing hěn dà.", meaning: "Her eyes are very big." },
    },
    {
      id: 12,
      title: "Family roles",
      vocab: [
        { hanzi: "妻子", pinyin: "qīzi", meaning: "wife" },
        { hanzi: "丈夫", pinyin: "zhàngfu", meaning: "husband" },
        { hanzi: "男孩", pinyin: "nánhái", meaning: "boy" },
        { hanzi: "女孩", pinyin: "nǚhái", meaning: "girl" },
        { hanzi: "阿姨", pinyin: "āyí", meaning: "auntie" },
      ],
      sentence: { hanzi: "我妻子是老师。", pinyin: "Wǒ qīzi shì lǎoshī.", meaning: "My wife is a teacher." },
    },
    {
      id: 13,
      title: "Snacks & drinks",
      vocab: [
        { hanzi: "牛奶", pinyin: "niúnǎi", meaning: "milk" },
        { hanzi: "羊肉", pinyin: "yángròu", meaning: "lamb" },
        { hanzi: "西瓜", pinyin: "xīguā", meaning: "watermelon" },
        { hanzi: "咖啡", pinyin: "kāfēi", meaning: "coffee" },
        { hanzi: "鸡", pinyin: "jī", meaning: "chicken" },
      ],
      sentence: { hanzi: "我喜欢喝牛奶。", pinyin: "Wǒ xǐhuan hē niúnǎi.", meaning: "I like drinking milk." },
    },
    {
      id: 14,
      title: "Things around me",
      vocab: [
        { hanzi: "鞋", pinyin: "xié", meaning: "shoes" },
        { hanzi: "报纸", pinyin: "bàozhǐ", meaning: "newspaper" },
        { hanzi: "房间", pinyin: "fángjiān", meaning: "room" },
        { hanzi: "房子", pinyin: "fángzi", meaning: "house" },
        { hanzi: "票", pinyin: "piào", meaning: "ticket" },
      ],
      sentence: { hanzi: "这是我的新鞋。", pinyin: "Zhè shì wǒ de xīn xié.", meaning: "These are my new shoes." },
    },
    {
      id: 15,
      title: "Getting around",
      vocab: [
        { hanzi: "火车", pinyin: "huǒchē", meaning: "train" },
        { hanzi: "自行车", pinyin: "zìxíngchē", meaning: "bicycle" },
        { hanzi: "公共汽车", pinyin: "gōnggòngqìchē", meaning: "bus" },
        { hanzi: "船", pinyin: "chuán", meaning: "boat" },
        { hanzi: "公里", pinyin: "gōnglǐ", meaning: "kilometer" },
      ],
      sentence: { hanzi: "我们坐火车去上海。", pinyin: "Wǒmen zuò huǒchē qù Shànghǎi.", meaning: "We take the train to Shanghai." },
    },
    {
      id: 16,
      title: "Outdoors",
      vocab: [
        { hanzi: "山", pinyin: "shān", meaning: "mountain" },
        { hanzi: "海", pinyin: "hǎi", meaning: "sea" },
        { hanzi: "河", pinyin: "hé", meaning: "river" },
        { hanzi: "树", pinyin: "shù", meaning: "tree" },
        { hanzi: "花", pinyin: "huā", meaning: "flower" },
      ],
      sentence: { hanzi: "山上有很多树。", pinyin: "Shān shàng yǒu hěn duō shù.", meaning: "There are many trees on the mountain." },
    },
    {
      id: 17,
      title: "Sky & some more",
      vocab: [
        { hanzi: "月亮", pinyin: "yuèliàng", meaning: "moon" },
        { hanzi: "太阳", pinyin: "tàiyáng", meaning: "sun" },
        { hanzi: "第一", pinyin: "dì-yī", meaning: "first" },
        { hanzi: "又", pinyin: "yòu", meaning: "again" },
        { hanzi: "些", pinyin: "xiē", meaning: "some, a few" },
      ],
      sentence: { hanzi: "今天的月亮真漂亮。", pinyin: "Jīntiān de yuèliàng zhēn piàoliang.", meaning: "Tonight's moon is really pretty." },
    },
    {
      id: 18,
      title: "Times of day",
      vocab: [
        { hanzi: "早上", pinyin: "zǎoshang", meaning: "morning" },
        { hanzi: "晚上", pinyin: "wǎnshang", meaning: "evening" },
        { hanzi: "小时", pinyin: "xiǎoshí", meaning: "hour" },
        { hanzi: "一会儿", pinyin: "yíhuìr", meaning: "a moment" },
        { hanzi: "一定", pinyin: "yídìng", meaning: "definitely" },
      ],
      sentence: { hanzi: "晚上我们一起吃饭吧。", pinyin: "Wǎnshang wǒmen yìqǐ chī fàn ba.", meaning: "Let's eat together this evening." },
    },
    {
      id: 19,
      title: "Ask away",
      vocab: [
        { hanzi: "怎么样", pinyin: "zěnmeyàng", meaning: "how about" },
        { hanzi: "哪里", pinyin: "nǎli", meaning: "where" },
        { hanzi: "是不是", pinyin: "shìbushì", meaning: "is it (or not)?" },
        { hanzi: "喂", pinyin: "wèi", meaning: "hello (phone)" },
        { hanzi: "啊", pinyin: "a", meaning: "(soft tone)" },
      ],
      sentence: { hanzi: "今天天气怎么样？", pinyin: "Jīntiān tiānqì zěnmeyàng?", meaning: "How's the weather today?" },
    },
    {
      id: 20,
      title: "Comparing",
      vocab: [
        { hanzi: "还是", pinyin: "háishì", meaning: "or (in questions)" },
        { hanzi: "或者", pinyin: "huòzhě", meaning: "or (in statements)" },
        { hanzi: "比", pinyin: "bǐ", meaning: "than, compared with" },
        { hanzi: "别", pinyin: "bié", meaning: "don't" },
        { hanzi: "已经", pinyin: "yǐjīng", meaning: "already" },
      ],
      sentence: { hanzi: "你喝茶还是喝咖啡？", pinyin: "Nǐ hē chá háishì hē kāfēi?", meaning: "Will you have tea or coffee?" },
    },
    {
      id: 21,
      title: "Directions & particles",
      vocab: [
        { hanzi: "从", pinyin: "cóng", meaning: "from" },
        { hanzi: "离", pinyin: "lí", meaning: "(distance) from" },
        { hanzi: "向", pinyin: "xiàng", meaning: "toward" },
        { hanzi: "过", pinyin: "guò", meaning: "(past particle)" },
        { hanzi: "着", pinyin: "zhe", meaning: "(continuous)" },
      ],
      sentence: { hanzi: "我从北京来。", pinyin: "Wǒ cóng Běijīng lái.", meaning: "I come from Beijing." },
    },
    {
      id: 22,
      title: "Pets & little bits",
      vocab: [
        { hanzi: "狗", pinyin: "gǒu", meaning: "dog" },
        { hanzi: "猫", pinyin: "māo", meaning: "cat" },
        { hanzi: "牛", pinyin: "niú", meaning: "cow" },
        { hanzi: "一点儿", pinyin: "yìdiǎnr", meaning: "a little" },
        { hanzi: "一下", pinyin: "yíxià", meaning: "briefly" },
      ],
      sentence: { hanzi: "我家有一只狗和两只猫。", pinyin: "Wǒ jiā yǒu yì zhī gǒu hé liǎng zhī māo.", meaning: "My family has a dog and two cats." },
    },
    {
      id: 23,
      title: "Find & try",
      vocab: [
        { hanzi: "找", pinyin: "zhǎo", meaning: "to look for" },
        { hanzi: "找到", pinyin: "zhǎodào", meaning: "to find" },
        { hanzi: "接", pinyin: "jiē", meaning: "to catch, pick up" },
        { hanzi: "试", pinyin: "shì", meaning: "to try" },
        { hanzi: "打", pinyin: "dǎ", meaning: "to hit, play" },
      ],
      sentence: { hanzi: "我找到我的书了。", pinyin: "Wǒ zhǎodào wǒ de shū le.", meaning: "I found my book." },
    },
    {
      id: 24,
      title: "Senses & knowing",
      vocab: [
        { hanzi: "觉得", pinyin: "juéde", meaning: "to feel, think" },
        { hanzi: "听见", pinyin: "tīngjiàn", meaning: "to hear" },
        { hanzi: "看见", pinyin: "kànjiàn", meaning: "to see" },
        { hanzi: "知道", pinyin: "zhīdào", meaning: "to know" },
        { hanzi: "还", pinyin: "hái", meaning: "still, also" },
      ],
      sentence: { hanzi: "我觉得这个很好。", pinyin: "Wǒ juéde zhège hěn hǎo.", meaning: "I think this is very good." },
    },
    {
      id: 25,
      title: "OK & class",
      vocab: [
        { hanzi: "行", pinyin: "xíng", meaning: "OK, that works" },
        { hanzi: "不行", pinyin: "bùxíng", meaning: "no good" },
        { hanzi: "开心", pinyin: "kāixīn", meaning: "happy" },
        { hanzi: "课", pinyin: "kè", meaning: "class, lesson" },
        { hanzi: "笑话", pinyin: "xiàohuà", meaning: "joke" },
      ],
      sentence: { hanzi: "他的笑话真好笑。", pinyin: "Tā de xiàohuà zhēn hǎoxiào.", meaning: "His joke is really funny." },
    },
    {
      id: 26,
      title: "Open & close",
      vocab: [
        { hanzi: "关", pinyin: "guān", meaning: "to close, turn off" },
        { hanzi: "久", pinyin: "jiǔ", meaning: "long (time)" },
        { hanzi: "关门", pinyin: "guānmén", meaning: "to close the door" },
        { hanzi: "开门", pinyin: "kāimén", meaning: "to open the door" },
        { hanzi: "卖", pinyin: "mài", meaning: "to sell" },
      ],
      sentence: { hanzi: "请关门，谢谢。", pinyin: "Qǐng guānmén, xièxie.", meaning: "Please close the door, thanks." },
    },
    {
      id: 27,
      title: "Trips",
      vocab: [
        { hanzi: "旅行", pinyin: "lǚxíng", meaning: "to travel" },
        { hanzi: "路口", pinyin: "lùkǒu", meaning: "intersection" },
        { hanzi: "边", pinyin: "biān", meaning: "side" },
        { hanzi: "次", pinyin: "cì", meaning: "time(s), occasion" },
        { hanzi: "公斤", pinyin: "gōngjīn", meaning: "kilogram" },
      ],
      sentence: { hanzi: "这是我第一次来。", pinyin: "Zhè shì wǒ dì-yī cì lái.", meaning: "This is my first time here." },
    },
    {
      id: 28,
      title: "Sports & schoolwork",
      vocab: [
        { hanzi: "足球", pinyin: "zúqiú", meaning: "soccer" },
        { hanzi: "比赛", pinyin: "bǐsài", meaning: "match, game" },
        { hanzi: "题", pinyin: "tí", meaning: "question, topic" },
        { hanzi: "问题", pinyin: "wèntí", meaning: "problem, question" },
        { hanzi: "张", pinyin: "zhāng", meaning: "(measure: flat)" },
      ],
      sentence: { hanzi: "我喜欢看足球比赛。", pinyin: "Wǒ xǐhuan kàn zúqiú bǐsài.", meaning: "I like watching soccer matches." },
    },
    {
      id: 29,
      title: "Class supplies",
      vocab: [
        { hanzi: "准备", pinyin: "zhǔnbèi", meaning: "to prepare" },
        { hanzi: "数", pinyin: "shǔ", meaning: "to count" },
        { hanzi: "件", pinyin: "jiàn", meaning: "(measure: items)" },
        { hanzi: "信", pinyin: "xìn", meaning: "letter (mail)" },
        { hanzi: "笔", pinyin: "bǐ", meaning: "pen" },
      ],
      sentence: { hanzi: "这是我的笔。", pinyin: "Zhè shì wǒ de bǐ.", meaning: "This is my pen." },
    },
    {
      id: 30,
      title: "People & feelings",
      vocab: [
        { hanzi: "大人", pinyin: "dàrén", meaning: "adult" },
        { hanzi: "小孩", pinyin: "xiǎohái", meaning: "child" },
        { hanzi: "课本", pinyin: "kèběn", meaning: "textbook" },
        { hanzi: "牛肉", pinyin: "niúròu", meaning: "beef" },
        { hanzi: "哭", pinyin: "kū", meaning: "to cry" },
      ],
      sentence: { hanzi: "别哭，没关系。", pinyin: "Bié kū, méi guānxi.", meaning: "Don't cry, it's OK." },
    },
  ],
};
