import type { Curriculum } from "./types";

export const hsk3: Curriculum = {
  level: "hsk3",
  label: "HSK 3",
  emoji: "🐉",
  lessons: [
    {
      id: 1,
      title: "Greetings & manners",
      vocab: [
        { hanzi: "您", pinyin: "nín", meaning: "you (polite)" },
        { hanzi: "欢迎", pinyin: "huānyíng", meaning: "to welcome" },
        { hanzi: "需要", pinyin: "xūyào", meaning: "to need" },
        { hanzi: "应该", pinyin: "yīnggāi", meaning: "should, ought to" },
        { hanzi: "解决", pinyin: "jiějué", meaning: "to solve" },
      ],
      sentence: { hanzi: "欢迎您来我家。", pinyin: "Huānyíng nín lái wǒ jiā.", meaning: "Welcome to my home." },
    },
    {
      id: 2,
      title: "School & study",
      vocab: [
        { hanzi: "教室", pinyin: "jiàoshì", meaning: "classroom" },
        { hanzi: "校长", pinyin: "xiàozhǎng", meaning: "principal" },
        { hanzi: "成绩", pinyin: "chéngjì", meaning: "grade, score" },
        { hanzi: "复习", pinyin: "fùxí", meaning: "to review" },
        { hanzi: "练习", pinyin: "liànxí", meaning: "to practice" },
      ],
      sentence: { hanzi: "我每天都复习汉字。", pinyin: "Wǒ měitiān dōu fùxí hànzì.", meaning: "I review characters every day." },
    },
    {
      id: 3,
      title: "Time expressions",
      vocab: [
        { hanzi: "以前", pinyin: "yǐqián", meaning: "before, previously" },
        { hanzi: "以后", pinyin: "yǐhòu", meaning: "after, later" },
        { hanzi: "刚才", pinyin: "gāngcái", meaning: "just now" },
        { hanzi: "马上", pinyin: "mǎshàng", meaning: "right away" },
        { hanzi: "终于", pinyin: "zhōngyú", meaning: "finally" },
      ],
      sentence: { hanzi: "我马上就来。", pinyin: "Wǒ mǎshàng jiù lái.", meaning: "I'm coming right away." },
    },
    {
      id: 4,
      title: "Frequency",
      vocab: [
        { hanzi: "经常", pinyin: "jīngcháng", meaning: "often" },
        { hanzi: "总是", pinyin: "zǒngshì", meaning: "always" },
        { hanzi: "一直", pinyin: "yìzhí", meaning: "all along, continuously" },
        { hanzi: "其实", pinyin: "qíshí", meaning: "actually" },
        { hanzi: "几乎", pinyin: "jīhū", meaning: "almost" },
      ],
      sentence: { hanzi: "她经常看书。", pinyin: "Tā jīngcháng kàn shū.", meaning: "She often reads books." },
    },
    {
      id: 5,
      title: "Travel basics",
      vocab: [
        { hanzi: "护照", pinyin: "hùzhào", meaning: "passport" },
        { hanzi: "行李箱", pinyin: "xínglǐxiāng", meaning: "suitcase" },
        { hanzi: "地铁", pinyin: "dìtiě", meaning: "subway" },
        { hanzi: "公园", pinyin: "gōngyuán", meaning: "park" },
        { hanzi: "地图", pinyin: "dìtú", meaning: "map" },
      ],
      sentence: { hanzi: "我坐地铁去公园。", pinyin: "Wǒ zuò dìtiě qù gōngyuán.", meaning: "I take the subway to the park." },
    },
    {
      id: 6,
      title: "Weather & seasons",
      vocab: [
        { hanzi: "刮风", pinyin: "guāfēng", meaning: "to be windy" },
        { hanzi: "下雪", pinyin: "xiàxuě", meaning: "to snow" },
        { hanzi: "季节", pinyin: "jìjié", meaning: "season" },
        { hanzi: "春", pinyin: "chūn", meaning: "spring" },
        { hanzi: "秋", pinyin: "qiū", meaning: "autumn" },
      ],
      sentence: { hanzi: "秋天经常刮风。", pinyin: "Qiūtiān jīngcháng guāfēng.", meaning: "It is often windy in autumn." },
    },
    {
      id: 7,
      title: "Animals",
      vocab: [
        { hanzi: "熊猫", pinyin: "xióngmāo", meaning: "panda" },
        { hanzi: "马", pinyin: "mǎ", meaning: "horse" },
        { hanzi: "鸟", pinyin: "niǎo", meaning: "bird" },
        { hanzi: "鱼", pinyin: "yú", meaning: "fish" },
        { hanzi: "羊", pinyin: "yáng", meaning: "sheep" },
      ],
      sentence: { hanzi: "熊猫很可爱。", pinyin: "Xióngmāo hěn kě'ài.", meaning: "Pandas are very cute." },
    },
    {
      id: 8,
      title: "Body & health",
      vocab: [
        { hanzi: "头", pinyin: "tóu", meaning: "head" },
        { hanzi: "脸", pinyin: "liǎn", meaning: "face" },
        { hanzi: "耳朵", pinyin: "ěrduo", meaning: "ear" },
        { hanzi: "感冒", pinyin: "gǎnmào", meaning: "to catch a cold" },
        { hanzi: "健康", pinyin: "jiànkāng", meaning: "healthy" },
      ],
      sentence: { hanzi: "他感冒了，头很疼。", pinyin: "Tā gǎnmào le, tóu hěn téng.", meaning: "He caught a cold; his head hurts." },
    },
    {
      id: 9,
      title: "Sports & hobbies",
      vocab: [
        { hanzi: "运动", pinyin: "yùndòng", meaning: "sports, exercise" },
        { hanzi: "游泳", pinyin: "yóuyǒng", meaning: "to swim" },
        { hanzi: "跑步", pinyin: "pǎobù", meaning: "to run, jog" },
        { hanzi: "篮球", pinyin: "lánqiú", meaning: "basketball" },
        { hanzi: "锻炼", pinyin: "duànliàn", meaning: "to work out" },
      ],
      sentence: { hanzi: "我每天早上跑步。", pinyin: "Wǒ měitiān zǎoshang pǎobù.", meaning: "I jog every morning." },
    },
    {
      id: 10,
      title: "Food & taste",
      vocab: [
        { hanzi: "面包", pinyin: "miànbāo", meaning: "bread" },
        { hanzi: "鸡蛋", pinyin: "jīdàn", meaning: "egg" },
        { hanzi: "甜", pinyin: "tián", meaning: "sweet" },
        { hanzi: "新鲜", pinyin: "xīnxiān", meaning: "fresh" },
        { hanzi: "饿", pinyin: "è", meaning: "hungry" },
      ],
      sentence: { hanzi: "我饿了，想吃面包。", pinyin: "Wǒ è le, xiǎng chī miànbāo.", meaning: "I'm hungry; I want bread." },
    },
    {
      id: 11,
      title: "Shopping",
      vocab: [
        { hanzi: "便宜", pinyin: "piányi", meaning: "cheap" },
        { hanzi: "贵", pinyin: "guì", meaning: "expensive" },
        { hanzi: "超市", pinyin: "chāoshì", meaning: "supermarket" },
        { hanzi: "选择", pinyin: "xuǎnzé", meaning: "to choose" },
        { hanzi: "付款", pinyin: "fùkuǎn", meaning: "to pay" },
      ],
      sentence: { hanzi: "这件衣服很便宜。", pinyin: "Zhè jiàn yīfu hěn piányi.", meaning: "This piece of clothing is cheap." },
    },
    {
      id: 12,
      title: "Work & jobs",
      vocab: [
        { hanzi: "公司", pinyin: "gōngsī", meaning: "company" },
        { hanzi: "经理", pinyin: "jīnglǐ", meaning: "manager" },
        { hanzi: "办公室", pinyin: "bàngōngshì", meaning: "office" },
        { hanzi: "会议", pinyin: "huìyì", meaning: "meeting" },
        { hanzi: "同事", pinyin: "tóngshì", meaning: "colleague" },
      ],
      sentence: { hanzi: "经理在办公室开会。", pinyin: "Jīnglǐ zài bàngōngshì kāihuì.", meaning: "The manager is having a meeting in the office." },
    },
    {
      id: 13,
      title: "Internet & devices",
      vocab: [
        { hanzi: "上网", pinyin: "shàngwǎng", meaning: "to go online" },
        { hanzi: "电子邮件", pinyin: "diànzǐ yóujiàn", meaning: "email" },
        { hanzi: "手机", pinyin: "shǒujī", meaning: "mobile phone" },
        { hanzi: "网站", pinyin: "wǎngzhàn", meaning: "website" },
        { hanzi: "新闻", pinyin: "xīnwén", meaning: "news" },
      ],
      sentence: { hanzi: "我用手机看新闻。", pinyin: "Wǒ yòng shǒujī kàn xīnwén.", meaning: "I use my phone to read news." },
    },
    {
      id: 14,
      title: "Feelings",
      vocab: [
        { hanzi: "难过", pinyin: "nánguò", meaning: "sad" },
        { hanzi: "担心", pinyin: "dānxīn", meaning: "to worry" },
        { hanzi: "害怕", pinyin: "hàipà", meaning: "afraid" },
        { hanzi: "兴奋", pinyin: "xīngfèn", meaning: "excited" },
        { hanzi: "满意", pinyin: "mǎnyì", meaning: "satisfied" },
      ],
      sentence: { hanzi: "妈妈对我的成绩很满意。", pinyin: "Māma duì wǒ de chéngjì hěn mǎnyì.", meaning: "Mom is very satisfied with my grades." },
    },
    {
      id: 15,
      title: "People & relationships",
      vocab: [
        { hanzi: "邻居", pinyin: "línjū", meaning: "neighbor" },
        { hanzi: "客人", pinyin: "kèrén", meaning: "guest" },
        { hanzi: "孩子", pinyin: "háizi", meaning: "child" },
        { hanzi: "兄弟", pinyin: "xiōngdì", meaning: "brothers" },
        { hanzi: "结婚", pinyin: "jiéhūn", meaning: "to marry" },
      ],
      sentence: { hanzi: "我和邻居是好朋友。", pinyin: "Wǒ hé línjū shì hǎo péngyou.", meaning: "My neighbor and I are good friends." },
    },
    {
      id: 16,
      title: "Adjectives 1",
      vocab: [
        { hanzi: "聪明", pinyin: "cōngming", meaning: "clever" },
        { hanzi: "认真", pinyin: "rènzhēn", meaning: "diligent, serious" },
        { hanzi: "努力", pinyin: "nǔlì", meaning: "to strive, hard-working" },
        { hanzi: "简单", pinyin: "jiǎndān", meaning: "simple" },
        { hanzi: "重要", pinyin: "zhòngyào", meaning: "important" },
      ],
      sentence: { hanzi: "她很聪明，也很努力。", pinyin: "Tā hěn cōngming, yě hěn nǔlì.", meaning: "She is smart and hard-working." },
    },
    {
      id: 17,
      title: "Adjectives 2",
      vocab: [
        { hanzi: "干净", pinyin: "gānjìng", meaning: "clean" },
        { hanzi: "安静", pinyin: "ānjìng", meaning: "quiet" },
        { hanzi: "舒服", pinyin: "shūfu", meaning: "comfortable" },
        { hanzi: "奇怪", pinyin: "qíguài", meaning: "strange" },
        { hanzi: "特别", pinyin: "tèbié", meaning: "special, especially" },
      ],
      sentence: { hanzi: "这家咖啡店很安静。", pinyin: "Zhè jiā kāfēidiàn hěn ānjìng.", meaning: "This café is very quiet." },
    },
    {
      id: 18,
      title: "Verbs of thought",
      vocab: [
        { hanzi: "相信", pinyin: "xiāngxìn", meaning: "to believe" },
        { hanzi: "记得", pinyin: "jìde", meaning: "to remember" },
        { hanzi: "忘记", pinyin: "wàngjì", meaning: "to forget" },
        { hanzi: "了解", pinyin: "liǎojiě", meaning: "to understand" },
        { hanzi: "决定", pinyin: "juédìng", meaning: "to decide" },
      ],
      sentence: { hanzi: "我决定去中国学习。", pinyin: "Wǒ juédìng qù Zhōngguó xuéxí.", meaning: "I decided to study in China." },
    },
    {
      id: 19,
      title: "Action verbs",
      vocab: [
        { hanzi: "搬", pinyin: "bān", meaning: "to move (objects)" },
        { hanzi: "借", pinyin: "jiè", meaning: "to borrow, lend" },
        { hanzi: "还", pinyin: "huán", meaning: "to return (sth)" },
        { hanzi: "送", pinyin: "sòng", meaning: "to give, deliver" },
        { hanzi: "拿", pinyin: "ná", meaning: "to take, hold" },
      ],
      sentence: { hanzi: "请把书还给我。", pinyin: "Qǐng bǎ shū huán gěi wǒ.", meaning: "Please return the book to me." },
    },
    {
      id: 20,
      title: "Verbs of speech",
      vocab: [
        { hanzi: "回答", pinyin: "huídá", meaning: "to answer" },
        { hanzi: "告诉", pinyin: "gàosu", meaning: "to tell" },
        { hanzi: "讨论", pinyin: "tǎolùn", meaning: "to discuss" },
        { hanzi: "介绍", pinyin: "jièshào", meaning: "to introduce" },
        { hanzi: "解释", pinyin: "jiěshì", meaning: "to explain" },
      ],
      sentence: { hanzi: "请你告诉我答案。", pinyin: "Qǐng nǐ gàosu wǒ dá'àn.", meaning: "Please tell me the answer." },
    },
    {
      id: 21,
      title: "Compare & change",
      vocab: [
        { hanzi: "比较", pinyin: "bǐjiào", meaning: "comparatively" },
        { hanzi: "更", pinyin: "gèng", meaning: "even more" },
        { hanzi: "最", pinyin: "zuì", meaning: "most" },
        { hanzi: "变化", pinyin: "biànhuà", meaning: "change" },
        { hanzi: "一样", pinyin: "yíyàng", meaning: "the same" },
      ],
      sentence: { hanzi: "今天比昨天更冷。", pinyin: "Jīntiān bǐ zuótiān gèng lěng.", meaning: "Today is even colder than yesterday." },
    },
    {
      id: 22,
      title: "Conjunctions",
      vocab: [
        { hanzi: "因为", pinyin: "yīnwèi", meaning: "because" },
        { hanzi: "所以", pinyin: "suǒyǐ", meaning: "so, therefore" },
        { hanzi: "虽然", pinyin: "suīrán", meaning: "although" },
        { hanzi: "但是", pinyin: "dànshì", meaning: "but" },
        { hanzi: "如果", pinyin: "rúguǒ", meaning: "if" },
      ],
      sentence: { hanzi: "虽然下雨，但是我还要去。", pinyin: "Suīrán xiàyǔ, dànshì wǒ hái yào qù.", meaning: "Although it's raining, I still want to go." },
    },
    {
      id: 23,
      title: "Numbers & amounts",
      vocab: [
        { hanzi: "百", pinyin: "bǎi", meaning: "hundred" },
        { hanzi: "千", pinyin: "qiān", meaning: "thousand" },
        { hanzi: "万", pinyin: "wàn", meaning: "ten thousand" },
        { hanzi: "半", pinyin: "bàn", meaning: "half" },
        { hanzi: "双", pinyin: "shuāng", meaning: "pair" },
      ],
      sentence: { hanzi: "我买了一双新鞋。", pinyin: "Wǒ mǎi le yì shuāng xīn xié.", meaning: "I bought a new pair of shoes." },
    },
    {
      id: 24,
      title: "Around the city",
      vocab: [
        { hanzi: "银行", pinyin: "yínháng", meaning: "bank" },
        { hanzi: "图书馆", pinyin: "túshūguǎn", meaning: "library" },
        { hanzi: "宾馆", pinyin: "bīnguǎn", meaning: "hotel" },
        { hanzi: "机场", pinyin: "jīchǎng", meaning: "airport" },
        { hanzi: "街道", pinyin: "jiēdào", meaning: "street" },
      ],
      sentence: { hanzi: "图书馆在银行旁边。", pinyin: "Túshūguǎn zài yínháng pángbiān.", meaning: "The library is next to the bank." },
    },
    {
      id: 25,
      title: "Cooking & taste",
      vocab: [
        { hanzi: "厨房", pinyin: "chúfáng", meaning: "kitchen" },
        { hanzi: "做饭", pinyin: "zuòfàn", meaning: "to cook" },
        { hanzi: "饺子", pinyin: "jiǎozi", meaning: "dumplings" },
        { hanzi: "面条", pinyin: "miàntiáo", meaning: "noodles" },
        { hanzi: "辣", pinyin: "là", meaning: "spicy" },
      ],
      sentence: { hanzi: "妈妈在厨房做饺子。", pinyin: "Māma zài chúfáng zuò jiǎozi.", meaning: "Mom is making dumplings in the kitchen." },
    },
    {
      id: 26,
      title: "Personality",
      vocab: [
        { hanzi: "热情", pinyin: "rèqíng", meaning: "enthusiastic" },
        { hanzi: "诚实", pinyin: "chéngshí", meaning: "honest" },
        { hanzi: "勇敢", pinyin: "yǒnggǎn", meaning: "brave" },
        { hanzi: "幽默", pinyin: "yōumò", meaning: "humorous" },
        { hanzi: "自己", pinyin: "zìjǐ", meaning: "self" },
      ],
      sentence: { hanzi: "她很热情，对每个人都好。", pinyin: "Tā hěn rèqíng, duì měi gè rén dōu hǎo.", meaning: "She is warm and kind to everyone." },
    },
    {
      id: 27,
      title: "Plans & goals",
      vocab: [
        { hanzi: "计划", pinyin: "jìhuà", meaning: "plan" },
        { hanzi: "希望", pinyin: "xīwàng", meaning: "hope" },
        { hanzi: "梦想", pinyin: "mèngxiǎng", meaning: "dream" },
        { hanzi: "成功", pinyin: "chénggōng", meaning: "success" },
        { hanzi: "机会", pinyin: "jīhuì", meaning: "chance, opportunity" },
      ],
      sentence: { hanzi: "我希望成为老师。", pinyin: "Wǒ xīwàng chéngwéi lǎoshī.", meaning: "I hope to become a teacher." },
    },
    {
      id: 28,
      title: "Music & art",
      vocab: [
        { hanzi: "音乐", pinyin: "yīnyuè", meaning: "music" },
        { hanzi: "唱歌", pinyin: "chànggē", meaning: "to sing" },
        { hanzi: "跳舞", pinyin: "tiàowǔ", meaning: "to dance" },
        { hanzi: "电影", pinyin: "diànyǐng", meaning: "movie" },
        { hanzi: "故事", pinyin: "gùshì", meaning: "story" },
      ],
      sentence: { hanzi: "她喜欢一边唱歌一边跳舞。", pinyin: "Tā xǐhuan yìbiān chànggē yìbiān tiàowǔ.", meaning: "She likes to sing and dance at the same time." },
    },
    {
      id: 29,
      title: "Festivals & gifts",
      vocab: [
        { hanzi: "节日", pinyin: "jiérì", meaning: "festival" },
        { hanzi: "春节", pinyin: "Chūnjié", meaning: "Spring Festival" },
        { hanzi: "礼物", pinyin: "lǐwù", meaning: "gift" },
        { hanzi: "生日", pinyin: "shēngrì", meaning: "birthday" },
        { hanzi: "蛋糕", pinyin: "dàngāo", meaning: "cake" },
      ],
      sentence: { hanzi: "春节我们吃饺子。", pinyin: "Chūnjié wǒmen chī jiǎozi.", meaning: "We eat dumplings at Spring Festival." },
    },
    {
      id: 30,
      title: "Wrap-up & encouragement",
      vocab: [
        { hanzi: "继续", pinyin: "jìxù", meaning: "to continue" },
        { hanzi: "加油", pinyin: "jiāyóu", meaning: "go! / keep going!" },
        { hanzi: "进步", pinyin: "jìnbù", meaning: "progress" },
        { hanzi: "完成", pinyin: "wánchéng", meaning: "to complete" },
        { hanzi: "经验", pinyin: "jīngyàn", meaning: "experience" },
      ],
      sentence: { hanzi: "加油！你一定会成功。", pinyin: "Jiāyóu! Nǐ yídìng huì chénggōng.", meaning: "Keep going! You will succeed." },
    },
  ],
};
